#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/tbg28/nrn/nrn/neuron_install/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/tbg28/nrn/nrn/neuron_install/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/tbg28/git_stage/AmygdalaTheta/code_archive/source_material/1000_cell_new/x86_64/.libs/libnrnmech.so" "$@"
