#!/usr/bin/python3
import click
import logging
import os

from clint.textui import puts, colored, indent

from manager import input_commands, tuning_commands

@click.group()
@click.option('--verbose', is_flag=True, default=False, help='Verbose printing')
@click.pass_context
def cli(ctx, verbose):
    
    if verbose:
        click.echo(colored.green('Verbose printing mode is on.'))

    ctx_obj = {}
    ctx_obj["verbose"] = verbose

    ctx.obj = ctx_obj


cli.add_command(input_commands.cli)
cli.add_command(tuning_commands.cli)

if __name__ == "__main__":
    cli()